apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: eks-demo-cluster
  region: us-east-1

nodeGroups:
  - name: nodegrp-1
    instanceType: t2.small
    desiredCapacity: 3
    ssh: # public existing key
      publicKeyName: demokey1